extends: "default"

ignore: |
  vendor/

rules:
  document-start:
    present: false
  brackets:
    max-spaces-inside-empty: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    min-spaces-inside: 1
  line-length: disable
  truthy: disable

yaml-files:
  - '*.yaml'
  - '*.yml'
